### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Saulis** [Saulis/components-1#4]
Jouni

| commit | file reference | pull request |  |
| --- | --- | --- | --- |
| 4e00de3b46d7f1879db3c9f5b45215d51edc98af | [.travis.yml#L5](https://github.com/Saulis/components-1/blob/4e00de3b46d7f1879db3c9f5b45215d51edc98af/.travis.yml#L5) | #2 | [![#2](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/Saulis/components-1/pull/2) |

**Comment by jouni** [comment]
Yes?
